version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"                 # Root of the repository
    schedule:
      interval: "monthly"	# Can be "daily", "weekly", or "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
